
[general]

	[general.ping]
		ping_shape = 1
		limit_to_one_ping_of_a_text = true
		green = 196
		default_ping_range = 0
		"term4/archer" = ""
		add_random_string = false
		"term1/tank" = ""
		change_ping_color = false
		ping_color = "255,78,134,139"
		red = 0
		limit_to_one_ping_per_player = false
		blue = 48
		"term2/mage" = ""
		"delete_ping_waypoints_after:" = 0
		mage_sheep_cooldown = true
		alpha = 2
		"device/healer" = ""
		selector = 0
		"term3/berserker" = ""
		percent_slider = 0.0
		default_ping_text = ""
		accept_pings = true

	[general.dungeons]
		"term4/archer" = ""
		color_picker = "255,0,0,255"
		e = "hewwo"
		"do_action!!!" = false
		"term1/tank" = ""
		m7_dragons_autoping = true
		password = ""
		"term2/mage" = ""
		"delete_ping_waypoints_after:" = 1000.0
		mage_sheep_cooldown = false
		"device/healer" = ""
		"term3/berserker" = ""
		text = ""
		p3_terms = false
		default_ping_text = ""

	[general.eeeeee]
		selector = 0
		percent_slider = 0.0

	[general.category]
		password = ""
		color_picker = "255,0,0,255"
		"do_action!!!" = false
		text = ""

	[general.party_commands]
		self_ping_command = true

["not_general!"]
	checkbox = false

