
[general]

	[general.ping]
		"delete_ping_waypoints_after:" = 10000
		selector = 0
		percent_slider = 0.0

	[general.dungeons]
		password = ""
		color_picker = "255,0,0,255"
		e = "hewwo"
		"delete_ping_waypoints_after:" = 1000.0
		"do_action!!!" = false
		text = ""

	[general.eeeeee]
		selector = 0
		percent_slider = 0.0

	[general.category]
		password = ""
		color_picker = "255,0,0,255"
		"do_action!!!" = false
		text = ""

["not_general!"]
	checkbox = false

