
[general]

	[general.ping]
		ping_shape = 0
		limit_to_one_ping_of_a_text = true
		default_ping_range = 0
		limit_to_one_ping_per_player = false
		"delete_ping_waypoints_after:" = 0
		selector = 0
		percent_slider = 0.0
		default_ping_text = ""
		ping_color = "255,78,134,139"

	[general.dungeons]
		password = ""
		color_picker = "255,0,0,255"
		e = "hewwo"
		"delete_ping_waypoints_after:" = 1000.0
		"do_action!!!" = false
		text = ""
		default_ping_text = ""

	[general.eeeeee]
		selector = 0
		percent_slider = 0.0

	[general.category]
		password = ""
		color_picker = "255,0,0,255"
		"do_action!!!" = false
		text = ""

["not_general!"]
	checkbox = false

